@echo off
rem install_stage.bat - stages a clean, install-ready copy of the build
rem output into MuiBuilderQt_install\install_src.
rem
rem Called from MuiBuilderQt.pro's win32 QMAKE_POST_LINK step as:
rem     cmd /c install_stage.bat "<DESTDIR>" "<INSTALL_SRC_DIR>"
rem
rem Kept as a static file rather than generated by qmake on purpose: the
rem wildcard patterns below (Makefile*, *.rc, *.h, *.*) need to survive
rem intact for robocopy's own parser to see them - living here, in a
rem plain .bat file that only cmd.exe ever reads, they never pass through
rem mingw32-make's own recipe-line shell (which, depending on PATH, may
rem not be cmd.exe - see MuiBuilderQt.pro's comments) at all. Mirrors
rem AmigaED's own install_stage.bat, minus the DOC/AmigaED-Examples
rem staging steps at the end - MuiBuilderQt has no equivalent folders.
rem
rem %~1/%~2 strip any surrounding quotes from the two arguments; the
rem "%1"/"%2" forms below re-quote them for robocopy, so spaces in either
rem path would be handled correctly too (even though neither currently
rem contains any).

set "SRC=%~1"
set "DEST=%~2"

if exist "%DEST%" rmdir /S /Q "%DEST%"
mkdir "%DEST%"

robocopy "%SRC%" "%DEST%" *.* /E /XD release /XF Makefile* .qmake.stash *.rc *.h /NFL /NDL /NJH /NP

rem robocopy's exit codes are bit-flags (0-7 = success in various shades,
rem 8+ = real failure) - always report plain success here so the calling
rem recipe line (and mingw32-make) never has to interpret them; robocopy's
rem own console output already shows what happened.
exit /b 0
